name: Build and Upload ECR image

on:
  push:
    branches:
      - main
      - develop
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (bootstrap)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::985539786063:role/gitops-infra-tf
          aws-region: us-west-2

      - name: Install TF
        run: |
          sudo apt update && sudo apt install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install -y terraform


      - name: Terraform Init
        run: terraform init

      - name: Import state
        run: |
          terraform import aws_iam_openid_connect_provider.this arn:aws:iam::985539786063:oidc-provider/token.actions.githubusercontent.com
          terraform import aws_iam_policy.deploy arn:aws:iam::985539786063:policy/ci-deploy-policy
          terraform import aws_iam_role.this arn:aws:iam::985539786063:role/github_oidc_role
  
      - name: Terraform Apply
        run: terraform apply -auto-approve
